version: '3'
services:

  frontproxy:
    image: linuxserver/letsencrypt
    container_name: frontproxy
    cap_add:
      - NET_ADMIN
    env_file:
      - ./env/frontproxy.env
    ports:
      - 44:443
    networks:
      - proxy
    volumes:
      - cert-config:/config
      - ./docker/proxy/openiot.subdomain.conf:/config/nginx/proxy-confs/openiot.subdomain.conf
      - certs:/etc/letsencrypt/live
    restart: unless-stopped

  openiot_web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    image: openiot:web
    container_name: web
    ports:
      - 9005:80
    networks:
      - web

volumes:
  letsencrypt-config:
  certs:
  cert-config:

networks:
  proxy:
  web:
